config/routes.rb
Rails.application.routes.draw do
 #後から記述
 root "books#top"
 #ここまで  
  resources :books
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    
validates :title, presence: true
    validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 #後から記述
  def top
  end
 #ここまで
  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  #string parameters定義

  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
  if @book.save
    flash[:notice] = "book was successfully created."
    redirect_to book_path(@book.id)
  else
    @books = Book.all
    render 'index'
  end
end

  def edit
    @book = Book.find(params[:id])
  end

 def update
   @book = Book.find(params[:id])
   if @book.update(book_params)
   flash[:notice] = "Book was successfully updated."
   redirect_to book_path(@book.id)
 else
   render 'edit'
   flash[:danger]= "Book"
 end
 end



  def destroy
    book = Book.find(params[:id])
   if book.destroy
    flash[:notice] = "Book was successfully destroyed."
    redirect_to books_path
  else
    render action: :new
  end
  end

   private
  def book_params
    params.require(:book).permit(:title, :body)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model:@book, local: true do |f| %>
<%= render 'layouts/error.message' ,book: f.object %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Update Book' %>
<% end %><!-- ここから下記述しました -->
<%= link_to "Show", book_path(@book) %> | <%= link_to "Back", books_path %>

app/views/books/index.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<header><h1>Books</h1></header>
<body>


  <table style="border:none;">
  <tbody style="border:none;">
    <tr style="border:none;">
      <td style="border:none;"><b>Title</b></td>
      <td style="border:none;"><b>Body</b></td></td>
    </tr>
     <% @books.each do |book| %>
    <tr style="border:none;">
      <td style="border:none;"><%= book.title %></td>
      <td style="border:none;"><%= book.body %></td>
      <td style="border:nine"><%= link_to "Show", book_path(book) %></td>
      <td style="border:nine"><%= link_to "Edit", edit_book_path(book) %></td>
      <td style="border:nine"><%= link_to "Destroy", book_path(book), method: :delete,  "data-confirm" =>"Are you sure？" %></td>
    </tr>
    <% end %>
  </tbody>
</table>


<!-- 入力フォーム -->
<h3>New Book</h3>
<!-- ここ　-->

<!--  ここ　-->

<!-- form_with部分 -->
 
<%= form_with model:@book, local:true do |f| %>
<%= render 'layouts/error.message' ,book: f.object %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>
</body>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<main>
 <p>Title:<%= @book.title %></p>
 <p>Body:<%= @book.body %></p>

 <!-- Editで編集ページへ -->
 <%= link_to "Edit", edit_book_path(@book.id) %>
 <!-- Backでindexへ戻る -->
      <%= link_to "Back", books_path %>
</main>

app/views/books/top.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <title>WebCampBackendNew</title>
  </head>

  <body>
    <header><h1>ようこそ Bookers へ！</h1></header>

    <main>
     <div class="text-box"><p class="text">
        <b>Bookers</b>では、さまざまな書籍に関するあなたの意見や
      </p>
      <p class="text">
        印象を共有し交換することができます
      </p>
      <p><%= link_to "start", books_path %></p></div>
    </main>
  </body>
</html> 

app/views/layouts/_error.message.html.erb
<% if book.errors.any? %>
  <div class="alert alert-warning">
    <div class="erro"><ul>error!
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %></div>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>